spring:
  datasource:
      url: jdbc:mysql://www.littleisle.cn:3306/my_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: always123.
  thymeleaf:
      mode: HTML5
server:
  port: 8181
mybatis:
  mapper-locations: classpath:mapping/*.xml