ureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-login
  datasource:
      url: jdbc:mysql://192.168.1.58:3306/my_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: shWHU666!
mybatis:
  mapper-locations: classpath:mapping/*.xml